fix OBSVerse
texttree/bsa pull request #125
Opened 2021-07-09 21:07 UTC by Valyukhov

2021-07-09 21:16 UTC, Valyukhov commented
I created frok from ru/gl/OBS_ru. And change it, But I didn't find how to include it in our app

2021-07-09 21:39 UTC, Vorobushec approved these changes

2021-07-10 10:47 UTC, Valyukhov commented on src/components/OBSVerses/OBSVerses.js
> +            text = _markdown[n * 2];
in this place i think, maybe I'm losing something.  I need to test this in unnormal OBS.
I try use /\(([^)]*)\)/g.test(_markdown[n * 2])[1]), but i got infinite loop and i set it like this.

2021-07-10 13:20 UTC, foxprogs commented on src/components/OBSVerses/OBSVerses.js
> +            text = _markdown[n * 2];
Если делаешь тест, то не надо [1] писать. Он возвращает тру или фолс

2021-07-12 03:46 UTC, foxprogs commented on src/components/OBSVerses/OBSVerses.js
> +            text = _markdown[n * 2];
Тут ты потерял один элемент. В блоке else надо text = _markdown[n * 2] + '\n' +  _markdown[n * 2 + 1];

2021-07-12 03:48 UTC, foxprogs requested changes
Еще там где ты выводишь уже эти блоки со стихами, надо поставить проверку. Если в urlImage ничего нет то не выводить код картинки

2021-07-12 11:25 UTC, Valyukhov commented on src/components/OBSVerses/OBSVerses.js
> +            text = _markdown[n * 2];
почему-то '\n' не разрывает строки, я уже и через шаблонные  `${_markdown[n * 2]} \n _markdown[n * 2 + 1] ` делал

2021-07-13 06:55 UTC, foxprogs commented on src/components/OBSVerses/OBSVerses.js
> +            text = _markdown[n * 2];
в штмл переносы строки и пробелы не работают. Нужно тогда написать <br />

2021-07-13 07:10 UTC, foxprogs commented on src/components/OBSVerses/OBSVerses.js
> +            text = _markdown[n * 2] + '\n' + _markdown[n * 2 + 1];
вроде все гуд. Только тут поставь тогда `<br />`

2021-07-13 07:12 UTC, foxprogs approved these changes

2021-07-13 09:43 UTC, Valyukhov commented on src/components/OBSVerses/OBSVerses.js
> +            text = _markdown[n * 2] + '\n' + _markdown[n * 2 + 1];
я переделал по-своему, надоело время терять и бороться с этими переносами ))

2021-07-13 09:44 UTC, merged