Feature tim added short cut
texttree/bsa pull request #130
Opened 2021-07-14 21:36 UTC by Vorobushec

2021-07-16 05:02 UTC, foxprogs commented on src/KeyboardShortcut.js
> +  document.onkeyup = (event) => {
У меня вопрос по поводу производительности.
На любое событие нажатия на кнопки будут сначала создаваться все эти переменные, и почему let а не const. Я бы разбил код на разные методы небольшие. Если обернуть все эти переменные в небольшой метод и вызывать уже по факту, когда сработало верное событие.

2021-07-16 05:06 UTC, foxprogs commented on src/KeyboardShortcut.js
> +  let uniqueBookID = new Set();
Если этот код - копипаста, то перенеси его в хэлпер. потому что копипаста это не гуд

2021-07-16 05:08 UTC, foxprogs commented on src/KeyboardShortcut.js
> +  let uniqueBookID = new Set();
и так же лучше вызывать по факту уже, внутри методов где эта переменная нужна

2021-07-16 06:16 UTC, foxprogs commented on src/KeyboardShortcut.js
> +        setReferenceSelected({
Этот блок кода не нужен, референс же остается неизменным.

2021-07-16 06:17 UTC, foxprogs commented on src/KeyboardShortcut.js
> +        chapterNumber++;
ее можно убрать

2021-07-16 06:17 UTC, foxprogs commented on src/KeyboardShortcut.js
> +          chapter: String(chapterNumber),
а тут написать String(++chapterNumber),

2021-07-16 06:18 UTC, foxprogs commented on src/KeyboardShortcut.js
> +        setReferenceSelected({
этот блок кода тоже не нужен, референс не меняется

2021-07-16 06:23 UTC, foxprogs requested changes
Может дело вкуса, но я немного запутался в иф/элс =)
У меня два предложения. 
1 - у тебя код внутри только устанавливает референс, может убрать его вниз. То есть сначала все проверки, в которых ты получаешь book и chapter. А потом внизу сделать один раз setReference. Тогда блоки с условиями были бы более компактны, и видно было бы, что там происходит. 
2 - если несколько else if {} блоков - то лучше стараться их заменять на switch case потому что он более понятен. Например так
if (event.ctrlKey){
  switch(event.code){
    case 'ArrowRight':
      goToNextChapter();
      break;
    case 'ArrowLeft':
      goToPrevChapter();
      break;
    case 'KeyH':
      openPassageMode();
      break;
и так далее, когда будут добавляться шорткеи.
а внутри просто несколько строк, вынести код в методы, опять же для удобства чтения.
  }
}
3. Может разделить как-то так
if (это ОБС) {} else {}
или 
if (это последняя глава) {} else {}
просто чтобы легче было читать код

2021-07-16 06:44 UTC, foxprogs commented
Еще один момент - меня смущает вот это import Shortcut from './KeyboardShortcut';
С заглавной буквы же не методы. Может сделать типа import { setShortcut } from './KeyboardShortcut';

2021-07-17 02:13 UTC, Valyukhov commented on src/KeyboardShortcut.js
> +        chapterNumber !== chapters.length &&
опять же, если верхний блок убрать, может просто оставить 
if (chapterNumber < chapters.length && referenceSelected.bookId !== 'obs')

2021-07-17 02:13 UTC, Valyukhov commented on src/KeyboardShortcut.js
> +        chapterNumber !== chapters.length &&
ну и после этих изменений, нужно в целом посмотреть на эту ёлочку из ifelse и либо упростить, либо оптимизировать, пока не вижу в целом, после предстоящих изменений, поэтому не могу дать конкретных рекомендаций

2021-07-19 10:18 UTC, foxprogs approved these changes

2021-07-19 10:20 UTC, merged

2021-07-19 10:21 UTC, Valyukhov approved these changes