move through chapters with swipes
texttree/bsa pull request #163
Opened 2021-09-13 15:56 UTC by Vorobushec

2021-09-13 18:22 UTC, foxprogs requested changes

2021-09-13 18:22 UTC, foxprogs commented on src/components/Swipes/Swipes.js
> +  }, [ref]);
тут лучше пустой массив, поставь просто чтобы линтер не ругался

2021-09-13 18:22 UTC, foxprogs commented on src/components/Swipes/Swipes.js
> +  });
и тут добавь тогда конфиг чтобы длину свайпа настроить

2021-09-13 19:39 UTC, Valyukhov approved these changes

2021-09-14 08:00 UTC, foxprogs approved these changes

2021-09-14 08:07 UTC, merged