Add pavel tim copy layout
texttree/bsa pull request #321
Opened 2022-03-24 07:38 UTC by Pavel064

## Changes proposed in this pull request:
 - copy layout
 - the ability to share the layout
 

`Has the changelog been added to what is being done in this pull request`

@foxprogs @Vorobushec @Valyukhov

2022-03-24 07:55 UTC, foxprogs commented on package.json
> +    "js-base64": "^3.7.2",
зачем это? Вы же не используете её

2022-03-24 08:03 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +import { useStyles } from './style';
сделайте пожалуйста порядок импортов как везде

2022-03-24 08:07 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +    }
поставьте проверки вверх. Сначала на пустое имя. Потом на повторяющееся. И если все ок то уже сохранение. Так визуально будет легче понять код

2022-03-24 08:12 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +      enqueueSnackbar(t('New_layout_saved'), { variant: 'success' });
Сделайте один стиль для ошибок. Вижу что у нас там сейчас нет стандарта. Все три вида. Давайте может чтобы без _ и все слова с заглавной.

2022-03-24 08:15 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +          source: bookId,
вам не нужен bookId, а нужно знать, это obs или нет. По этому тут булево сделайте, isOBS.

2022-03-24 08:16 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +      setAppConfig(value);
если вместо source будет булево, то тогда тут одним условием можно обойтись

2022-03-24 08:19 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +  const deleteLayout = useCallback(
может остальные тоже в useCallback поместить

2022-03-24 08:25 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +                }}
может тут просто copyHandle создать. А то часть тут прописана, часть в copyToClipboard. Тогда и copyToClipboard можно убрать например, если он один раз встречается. Или оставить, на ваше усмотрение.

2022-03-24 08:25 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +                }}
тут тоже убрать код, добавить просто deleteHandle

2022-03-24 08:27 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +                <InputLabel shrink id="themeId">
id же не используете

2022-03-24 08:28 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +                  label={t('Layout_List')}
имя

2022-03-24 08:28 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +          {t('SaveLayoutBtn')}
Button лучше написать. Кто будет переводить, может не знать что такое btn

2022-03-24 08:30 UTC, foxprogs commented on src/components/CopyLayout/style.js
> +  menuItemLayoutList: {
это где-то используется? проверьте и удалите лишние

2022-03-24 08:31 UTC, foxprogs commented on src/components/CopyLayout/style.js
> +      color: 'blue',
замените на значения из темы

2022-03-24 08:34 UTC, foxprogs commented on src/components/Settings/Settings.js
> +import { CopyLayout } from '../../components';
объедините все компоненты. А то они тут в 4 местах добавляются и всезде по разному

2022-03-24 08:36 UTC, foxprogs commented on src/config/locales/ru/translation.json
> +  "WarningNonCorrectLayout": "Не корректно заполненное поле ввода макета",
"поле ввода макета" лучше переформулировать)

2022-03-24 08:37 UTC, foxprogs requested changes
написал комменты

2022-03-24 20:50 UTC, Valyukhov commented on src/components/CopyLayout/CopyLayout.js
> +      setLayoutStorage((prev) => {
![изображение](https://user-images.githubusercontent.com/74174349/160000449-2eaf3e96-46c1-45bd-bc3e-80cb314c3498.png)
Если удалить выделенный лэйаут - приложение сломается. Либо запретить это делать, либо предупредить и сделать резет

2022-03-24 20:50 UTC, Valyukhov commented on src/components/CopyLayout/CopyLayout.js
> +  const [currentSelected, setCurrentSelected] = useState(0);
![изображение](https://user-images.githubusercontent.com/74174349/160007382-6a90b8f8-8e3b-4b28-810f-a27fd79c7c27.png)
немного непонятно с текущим макетом. Я сохраняю 1, 2 и 3 макеты, загружаю третий макет, потом выхожу и захожу в настройки - макет показывает первый, но по факту это третий. и я не могу выбрать первый, потому что он уже выделен и не кликабелен, мне нужно выделить другой, потом только первый.
Возможно потому что при каждой  отработке компонента обнуляется currentSelected. Либо поднять его выше, чтобы он хранился не здесь, либо поменять логику надо, чтобы не запутать.

2022-03-24 20:52 UTC, Valyukhov commented
Пока прошелся по работе компонента. Пробовал его первый раз. Моменты указал, которые не корректно работают, лучше такое исправить. По коду вроде @foxprogs уже отметил. Пока добавить нечего

2022-03-24 21:13 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +  const [currentSelected, setCurrentSelected] = useState(0);
@Valyukhov если ты выбрал 3 лэйаут а потом поменял размер карточки - теперь это же уже не третий. Может тогда в этом списке сделать первый пункт какой-то не активный и не кликабельный, где был бы какой-то заголовок к примеру

2022-03-24 21:14 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +    if (checkingNameLayout && nameLayout !== '') {
да, trim так не написали

2022-03-25 04:49 UTC, Pavel064 commented on src/components/CopyLayout/style.js
> +  menuItemLayoutList: {
всё используется, проверил

2022-03-25 04:50 UTC, Pavel064 commented on src/components/CopyLayout/style.js
> +      color: 'blue',
готово!

2022-03-25 04:50 UTC, Pavel064 commented on src/components/Settings/Settings.js
> +import { CopyLayout } from '../../components';
готово

2022-03-25 04:50 UTC, Pavel064 commented on src/config/locales/ru/translation.json
> +  "WarningNonCorrectLayout": "Не корректно заполненное поле ввода макета",
готово

2022-03-25 04:52 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +          {t('SaveLayoutBtn')}
готово

2022-03-25 04:58 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +                  label={t('Layout_List')}
имя заменить чем-то?

2022-03-25 05:00 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +                <InputLabel shrink id="themeId">
готово

2022-03-25 05:09 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +  const deleteLayout = useCallback(
готово

2022-03-25 05:39 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +      enqueueSnackbar(t('New_layout_saved'), { variant: 'success' });
исправил, но только в нашем компоненте

2022-03-25 05:40 UTC, Pavel064 commented on package.json
> +    "js-base64": "^3.7.2",
готово

2022-03-25 06:26 UTC, Valyukhov commented on src/components/CopyLayout/CopyLayout.js
> +      setLayoutStorage((prev) => {
возможно в 78 строчке надо сделать проверку

2022-03-25 06:45 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +                  label={t('Layout_List')}
> имя заменить чем-то?

подошвы заменить на кэмэлкейс

2022-03-25 10:50 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +    }
готово

2022-03-25 13:31 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +          source: bookId,
готово

2022-03-25 14:49 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +      setAppConfig(value);
не могу понять, как переписать

2022-03-25 19:38 UTC, foxprogs commented on src/config/locales/ru/translation.json
> +  "INVALIDFORMAT": "неверный формат (проверьте, правильно ли Вы скопировали)",
надо поменять на Some_variable_name

2022-03-25 20:06 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +      } else {
это можно объединить в одно условие (isCurrentOBS === isOBS)

2022-03-25 20:10 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +    }
@Pavel064 не вижу этого исправления

2022-03-25 20:11 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +
доабавь еще тут проверку лейаута, чтобы не повторялся

2022-03-25 20:14 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +      const isCurrentOBS = bookId === 'obs';
в 36 строке у тебя уже же есть эта переменная isOBS. а в 70 ты ее переопределешь выходит

2022-03-25 20:16 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +        return (
добавь сюда сравнение лейаутов, чтобы нужный пункт в селекте активный был

2022-03-25 20:18 UTC, foxprogs commented on src/components/CopyLayout/CopyLayout.js
> +
ну и trim тоже не забудь добавить

2022-03-25 20:25 UTC, foxprogs commented on src/components/CopyLayout/style.js
> +      color: theme.palette.buttonCopy.main,
не обязательно свои цвета устанавливать, можно взять стандартные https://v4.mui.com/ru/customization/palette/#default-values

2022-03-25 20:26 UTC, foxprogs commented on src/components/CopyLayout/style.js
> +    marginLeft: '10px',
https://v4.mui.com/ru/customization/spacing/ вот так лучше отступы указывать

2022-03-25 21:30 UTC, foxprogs commented on src/components/CopyLayout/DownloadLayout.js
> +function DownloadLayout() {
А почему компонент Download лежит в папке Copy. Надо новую папку для него

2022-03-25 21:31 UTC, foxprogs commented on src/components/Settings/Settings.js
>  import SwitchChunks from './SwitchChunks';
почему он отдельно лежит тут а SwitchWordPopover например выше добавлен

2022-03-25 21:37 UTC, foxprogs commented on src/themes.js
> +    },
можно убрать и попробовать стандартные цвета использовать, error, success

2022-03-25 21:44 UTC, foxprogs commented on src/components/CopyLayout/DownloadLayout.js
> +    }
надо переписать, какие-то лишние условия

2022-03-25 21:46 UTC, foxprogs commented on src/components/CopyLayout/DownloadLayout.js
> +              name="comment"
лишнее

2022-03-25 21:46 UTC, foxprogs commented on src/components/CopyLayout/DownloadLayout.js
> +              id="outlined-basic"
лишнее

2022-03-25 21:49 UTC, foxprogs commented on src/components/CopyLayout/DownloadLayout.js
> +        }}
вынести в какой-нить handleClose

2022-03-25 21:50 UTC, foxprogs commented on src/components/CopyLayout/DownloadLayout.js
> +          }}
созддать обработчик самому

2022-03-25 21:52 UTC, foxprogs commented on src/components/CopyLayout/DownloadLayout.js
> +  const importLayout = () => {
добавь еще сравнение, есть ли такой лейаут, сохранен ли

2022-03-28 08:25 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +    if (checkingNameLayout && nameLayout !== '') {
готово

2022-03-28 14:49 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +  const [currentSelected, setCurrentSelected] = useState(0);
готово

2022-03-28 15:04 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +      } else {
готово

2022-03-28 15:16 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +
готово

2022-03-28 15:20 UTC, Pavel064 commented on src/components/CopyLayout/CopyLayout.js
> +        return (
готово

2022-03-28 15:32 UTC, Pavel064 commented on src/components/CopyLayout/style.js
> +    marginLeft: '10px',
готово

2022-03-28 15:40 UTC, Pavel064 commented on src/components/Settings/Settings.js
>  import SwitchChunks from './SwitchChunks';
готово

2022-03-28 15:45 UTC, Pavel064 commented on src/components/CopyLayout/style.js
> +      color: theme.palette.buttonCopy.main,
готово

2022-03-28 15:45 UTC, Pavel064 commented on src/themes.js
> +    },
готово

2022-03-28 15:49 UTC, Pavel064 commented on src/components/CopyLayout/DownloadLayout.js
> +    }
готово

2022-03-28 15:50 UTC, Pavel064 commented on src/components/CopyLayout/DownloadLayout.js
> +              name="comment"
готово

2022-03-28 16:09 UTC, Pavel064 commented on src/components/CopyLayout/DownloadLayout.js
> +        }}
готово

2022-03-28 16:10 UTC, Pavel064 commented on src/components/CopyLayout/DownloadLayout.js
> +          }}
готово

2022-03-29 06:48 UTC, Pavel064 commented on src/config/locales/ru/translation.json
> +  "INVALIDFORMAT": "неверный формат (проверьте, правильно ли Вы скопировали)",
готово

2022-03-29 07:06 UTC, Pavel064 commented on src/components/CopyLayout/DownloadLayout.js
> +function DownloadLayout() {
готово

2022-03-29 07:13 UTC, foxprogs commented on src/components/CopyLayout/index.js
> +export { default as DownloadLayout } from '../DownloadLayout/DownloadLayout';
убрать

2022-03-29 07:14 UTC, foxprogs commented on src/components/DownloadLayout/index.js
> +export { default as DownloadLayout } from '../DownloadLayout/DownloadLayout';
поменять экспорт

2022-03-29 07:14 UTC, foxprogs commented on src/components/DownloadLayout/DownloadLayout.js
> +import { useStyles } from '../DownloadLayout/style';
исправить импорт

2022-03-29 10:27 UTC, Valyukhov commented
Looks good!  you need to add new feature in ChangeLog

2022-03-29 10:28 UTC, Valyukhov approved these changes

2022-03-29 22:16 UTC, foxprogs commented
@Pavel064 @Vorobushec @Valyukhov Остается подправить дизайн и можно мерджить

2022-03-31 14:06 UTC, foxprogs approved these changes

2022-03-31 14:09 UTC, merged