Fix OBS Parser
texttree/bsa pull request #356
Opened 2022-04-14 05:24 UTC by Valyukhov

2022-04-14 06:03 UTC, Valyukhov commented
@Vorobushec , I fixed this, but this story have 2 lines brake in the end. This is not cool. I haven't figured out how to fix this in OBS content. But i have found this just in 1 place. Maybe you can fix this in git.door43?
https://git.door43.org/Door43-Catalog/tg_obs/src/branch/master/content/01.md

2022-04-14 10:46 UTC, foxprogs commented on src/components/OBSVerses/OBSContent.js
> +    let _markdown = md.replaceAll('\u200B', '').split(/\n{2,}[\s]*/);
may be this \n\s*\n\s*

2022-04-14 11:03 UTC, Valyukhov commented on src/components/OBSVerses/OBSContent.js
> +                  <sup>{key.toString()}</sup> {el}
вынести за массив <sup>

2022-04-20 17:02 UTC, Valyukhov commented on src/components/OBSVerses/OBSContent.js
> +    let _markdown = md.replaceAll('\u200B', '').split(/\n{2,}[\s]*/);
@foxprogs 
это вместо .replaceAll('\u200B', '').split(/\n{2,}[\s]*/)?
просто split(/\n\s*\n\s*/)?
у меня не сработало

2022-04-20 17:36 UTC, Valyukhov commented on src/components/OBSVerses/OBSContent.js
> +    let _markdown = md.replaceAll('\u200B', '').split(/\n{2,}[\s]*/);
я оставил replace и внес новую регулярку

2022-04-26 08:16 UTC, Vorobushec approved these changes

2022-04-26 08:19 UTC, Pavel064 approved these changes

2022-04-27 12:43 UTC, foxprogs commented on src/components/OBSVerses/style.js
>    root: {
может вместо root назвать circular?

2022-04-27 12:48 UTC, foxprogs commented on src/components/OBSVerses/OBSContent.js
> +                  <span
давай сделаем тут div например. Не знаю в плане валидности, нормально ли, что внутри p находится div. Но суть в том, что тут у нас несколько строк текста, и может быть отобразить тут так же, в нескольких строках, вместо одной.

2022-04-27 12:49 UTC, foxprogs commented on src/components/OBSVerses/OBSContent.js
> +                    }}
Это надо вынести в тег p который все оборачивает. Иначе ты тут будешь копировать только одну строку из стиха.

2022-04-27 12:50 UTC, foxprogs requested changes
Need fix

2022-04-27 20:19 UTC, Valyukhov commented on src/components/OBSVerses/OBSContent.js
> +                  <span
span делал, чтобы склеить sup , теперь sup отдельно

2022-04-27 20:20 UTC, Valyukhov commented on src/components/OBSVerses/OBSContent.js
> +                  <span
![изображение](https://user-images.githubusercontent.com/74174349/165624152-e6c23142-82b5-4790-8766-13aec55ac5a6.png)

2022-04-28 13:19 UTC, Valyukhov commented
fix #355

2022-04-28 13:19 UTC, merged